import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { Bot, Cpu, Sparkles, AlertCircle } from "lucide-react";

export const metadata = {
  title: "AI Transparency & Model Policy | AIZONET",
  description: "Read our transparency disclosure regarding model usage, RAG vector caching, and ranking priority models.",
};

export default function TransparencyPage() {
  return (
    <div className="flex flex-col min-h-screen bg-[#030308]">
      <Navbar />
      
      <main className="flex-1 relative py-20 px-4 md:px-8">
        <div className="absolute inset-0 bg-mesh opacity-40 pointer-events-none" />
        <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px] pointer-events-none" />

        <div className="max-w-4xl mx-auto relative z-10">
          {/* Header section */}
          <div className="text-center mb-16">
            <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-2xl border border-primary/20 text-primary mb-6">
              <Bot className="w-8 h-8" />
            </div>
            <h1 className="font-heading text-4xl md:text-5xl font-black text-white mb-4">
              AI & Model <span className="text-gradient">Transparency</span>
            </h1>
            <p className="text-white/40 text-sm">
              Publishing Standards • Technical AI Safeguards • Raipur AI Lab Disclosures
            </p>
          </div>

          {/* Grid cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 mb-12">
            <div className="glass-dark border border-white/5 p-6 rounded-2xl">
              <Cpu className="w-6 h-6 text-primary mb-4" />
              <h3 className="text-white font-bold mb-2">Hybrid Models</h3>
              <p className="text-white/50 text-sm leading-relaxed">
                Utilizing state-of-the-art architectures (GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro) depending on speed/accuracy requirements.
              </p>
            </div>
            <div className="glass-dark border border-white/5 p-6 rounded-2xl">
              <Sparkles className="w-6 h-6 text-accent mb-4" />
              <h3 className="text-white font-bold mb-2">Semantic Caching</h3>
              <p className="text-white/50 text-sm leading-relaxed">
                Matches previous successful queries via cosine similarity to minimize token latencies and prevent model hallucinations.
              </p>
            </div>
            <div className="glass-dark border border-white/5 p-6 rounded-2xl">
              <AlertCircle className="w-6 h-6 text-yellow-400 mb-4" />
              <h3 className="text-white font-bold mb-2">Human Control</h3>
              <p className="text-white/50 text-sm leading-relaxed">
                All generated content, outlines, and cold sales templates must pass human-in-the-loop validation prior to deployment.
              </p>
            </div>
          </div>

          {/* Document Content */}
          <div className="glass-dark border border-white/5 p-8 md:p-12 rounded-3xl space-y-8 text-white/75 leading-relaxed text-sm md:text-base">
            <section>
              <h2 className="text-xl font-bold text-white mb-3">Our Core Principles for AI Operations</h2>
              <p>
                As AI systems scale, trust becomes the primary commodity. At AIZONET, we believe that AI should empower creators and analysts, not replace authentic human E-E-A-T signals.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. How We Generate Outlines & Content</h2>
              <p>
                Our AI content agent generates structures based on SERP crawler scrapers and real ranking pages. It extracts keyword gaps, visualizes competitors headings densities, and targets search intent. The actual text generated is parsed with local validators to check for grammatical completeness, reading difficulty levels, and alignment with modern editorial standards.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. Deductive Scoring Metrics</h2>
              <p>
                The priority metrics (ROI estimators, SEO confidence ratings) generated by AIZONET OS are based on deterministic mathematical priority calculations matching search volumes against target difficulties, rather than subjective predictions. This guarantees mathematical trust.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. Crawling & Processing Safeguards</h2>
              <p>
                We do not scrape private directories or access user-restricted subpages. Our crawler adheres strictly to the robots.txt standards and includes standard safety pauses of 500ms to avoid raising alarms or slowing down your servers.
              </p>
            </section>

            <section className="pt-6 border-t border-white/5">
              <p className="text-white/50 text-xs text-center">
                For detailed scientific inquiries on our vector schemas, contact: <strong>engineering@aizonet.in</strong> • Chhattisgarh, India.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
